export const surpriseMePrompts = [
  "A glamorous studio portrait of a woman with glowing skin, sharp cheekbones, and emerald green eyes, wearing an elegant red gown, soft-focus background, and cinematic lighting.",
  "A serene mountain landscape with snow-capped peaks reflecting on a crystal-clear lake at sunrise, soft mist floating over the water, vibrant and natural colors, hyper-realistic",
  "A dense tropical rainforest scene with beams of sunlight breaking through the canopy, vibrant green foliage, moss-covered trees, and a crystal-clear stream winding through the frame",
  "A bustling street market at night in Tokyo, glowing neon signs in vibrant colors, people walking under umbrellas, and reflections shimmering on the wet pavement, ultra-detailed",
  "A candid black-and-white shot of a man sitting on a bench in a European cobblestone street, surrounded by pigeons, with soft natural lighting and a moody vintage tone",
  "A futuristic skyscraper with reflective glass panels under a vibrant sunset sky, captured at an upward angle, with stunning details and dynamic lighting",
  "An abandoned Gothic cathedral with ivy creeping up its walls, intricate stained glass windows, and dramatic sunlight streaming through broken arches, hyper-realistic and moody",
  "An extreme close-up of a dew-covered butterfly perched on a vibrant flower, with soft-focus background and intricate details of its wings and textures",
  "A crystal-clear macro shot of a droplet of water hanging from a leaf, refracting the colorful landscape in the background, with razor-sharp detail and smooth bokeh",
  "A majestic lion standing on a rocky outcrop at dusk, its mane flowing in the wind, with the savanna and a dramatic golden sunset in the background, hyper-realistic",
  "A snowy owl mid-flight over a frozen tundra, with feathers sharply detailed and icy air visibly swirling in the soft light, a highly detailed and natural composition",
  "A high-fashion editorial shot of a model in a flowing black gown standing in the middle of a desert, windswept hair, dramatic lighting, and a moody overcast sky",
  "A futuristic runway shoot with a model wearing avant-garde metallic clothing, neon lighting casting sharp shadows, and a sleek industrial background",
  "A dynamic action shot of a soccer player mid-kick during a match, dirt flying off the ground, intense facial expression, and a vibrant stadium background",
  "A cyclist speeding through a misty forest trail at sunrise, with motion blur in the background and sharp focus on the athlete and their gear",
  "A serene underwater view of a sea turtle gliding above a sandy ocean floor, with the surface rippling in the background and vivid blue tones",
  "An aerial view of a winding mountain road cutting through lush green valleys, with cars creating dynamic motion and dramatic shadows from the setting sun",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A drone shot of a tropical island surrounded by turquoise waters, white sandy beaches, and colorful coral reefs, with boats creating trails in the water",
  "A photo of a white fur monster standing in a purple room",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A breathtaking aerial view of a city skyline at twilight, with skyscrapers glowing in golden hues, reflections on the river, and a soft gradient sky, ultra-detailed and cinematic.",
  "A mysterious cyberpunk alleyway at night, neon signs casting vibrant colors, steam rising from grates, and a lone figure in a futuristic jacket walking through the scene, hyper-realistic.",
  "A mystical enchanted forest at dusk, with glowing bioluminescent plants, ethereal mist, and ancient twisted trees, a magical and atmospheric composition.",
  "A roaring waterfall cascading into a hidden jungle pool, surrounded by lush tropical vegetation, with sunlight streaming through the dense canopy, hyper-realistic and vibrant.",
  "A majestic bald eagle soaring above a vast canyon, with its wings fully extended, golden sunlight highlighting its feathers, and a dramatic sky in the background.",
  "A stunning futuristic cityscape with sleek, towering skyscrapers, flying vehicles, and neon holographic billboards, set under a vibrant dusk sky, ultra-detailed and dynamic.",
  "An astronaut standing on the surface of an alien planet, with a massive ringed gas giant in the sky, glowing blue crystals scattered across the rocky terrain, hyper-realistic sci-fi.",
  "A dramatic black-and-white portrait of a jazz musician playing the saxophone, smoke curling in the air, with moody lighting and a vintage film noir aesthetic.",
  "A stormy ocean scene with towering waves crashing against jagged rocks, a lighthouse standing resilient in the background, and dark, ominous clouds overhead, hyper-realistic.",
  "A vibrant carnival scene at night, with a Ferris wheel illuminated in rainbow lights, bustling crowds, and colorful confetti floating through the air, ultra-detailed and dynamic.",
  "A warrior in ancient samurai armor standing in a misty bamboo forest, katana in hand, with falling cherry blossoms and soft golden light filtering through the trees.",
  "A sleek futuristic race car speeding down a neon-lit highway, motion blur emphasizing its velocity, with a cyberpunk city in the background, ultra-detailed and dynamic.",
  "A tranquil autumn park scene with golden leaves covering the ground, a wooden bench under a vintage streetlamp, and a soft, warm glow from the evening sun.",
  "A surreal dreamscape with floating islands covered in lush greenery, waterfalls cascading into the sky, and a giant moon illuminating the ethereal landscape highly detailed digital art.",
  "A lone Viking warrior standing atop a snowy mountain peak, his fur cloak billowing in the wind, with a breathtaking view of a frozen fjord below, hyper-realistic and cinematic.",
  "A group of penguins waddling across an icy landscape, with the aurora borealis shimmering in the night sky, and a vast frozen ocean stretching into the horizon, ultra-detailed and natural.",
  "A dynamic parkour athlete mid-air between two skyscrapers, with city lights glowing below, captured in a breathtaking action shot with intense motion and energy.",
  "An elegant black panther prowling through a moonlit jungle, its sleek fur glistening, with glowing eyes and mist swirling around its powerful silhouette, hyper-realistic.",
  "A rustic countryside cottage covered in ivy, with warm light glowing from the windows, surrounded by a field of colorful wildflowers, and a dreamy sunset sky in the background.",
  "A post-apocalyptic desert wasteland with a lone survivor walking past rusted abandoned vehicles, sandstorms swirling, and a distant ruined city on the horizon, hyper-realistic.",
  "A celestial scene featuring a massive spiral galaxy with vibrant hues of blue and purple, countless stars, and glowing nebulae stretching across space, ultra-detailed and cosmic.",
  "A steampunk-inspired airship floating above a sprawling Victorian-era city, with intricate brass details, large propellers, and billowing clouds in the golden sunset sky, highly detailed.",
  "A breathtaking sunset over a crystal-clear lake, surrounded by towering snow-capped mountains and cherry blossoms in full bloom. 8K, ultra-sharp, vibrant colors.",
  "An enchanted forest with glowing bioluminescent mushrooms, fireflies swirling around an ancient, mystical tree. Hyper-detailed, magical ambiance.",
  "A tropical paradise island at sunrise, golden light reflecting off the turquoise waters, palm trees swaying gently. Photorealistic, stunning composition.",
  "A sleek, cybernetic humanoid with glowing blue circuits, standing in a high-tech neon-lit cityscape. Ultra-sharp, high-definition, cinematic glow.",
  "A futuristic spaceship hovering over a distant alien planet, twin suns setting behind towering crystal spires. Sci-fi concept art, ultra-detailed.",
  "A robotic samurai warrior with a plasma katana, standing on a neon-lit rooftop in a cyberpunk metropolis. Hyper-detailed, cinematic lighting.",
  "A breathtaking waterfall cascading down glowing crystal cliffs, surrounded by lush, otherworldly flowers that emit soft luminescence. Dreamlike, ultra-detailed, 8K.",
  "A golden wheat field swaying under a pastel-colored sunset, with a lonely windmill standing tall against the horizon. Soft lighting, serene, ultra-detailed.",
  "A floating island in the sky, with a massive ancient tree growing at its center, surrounded by waterfalls that pour into the clouds below. High-resolution, fantasy art.",
  "A hidden valley filled with massive, iridescent butterflies fluttering around enchanted glowing flowers, bathed in soft moonlight. Ultra-detailed, fantasy concept.",
  "A lone vampire queen with piercing silver eyes, standing in the ruins of a gothic cathedral under a crimson blood moon, her dark cloak billowing in the wind. High-resolution, dark fantasy.",
  "A cursed pirate ship drifting through an eerie mist, its tattered black sails glowing faintly with ghostly blue runes. Cinematic lighting, ultra-detailed, 8K.",
  "A mysterious cloaked figure holding a lantern, standing at the edge of a foggy forest with twisted trees and glowing red eyes peering from the shadows. Dark fantasy, ultra-detailed.",
  "A majestic black dragon with glowing red eyes perched atop a ruined castle, watching over a stormy battlefield under a full moon. Cinematic, epic fantasy, high-resolution.",
  "A celestial phoenix rising from a cosmic nebula, its radiant feathers glowing with swirling galaxies and star dust. 8K, ultra-detailed, cinematic lighting.",
  "A mystical mermaid queen sitting on a coral throne, surrounded by glowing bioluminescent sea creatures, her shimmering scales reflecting deep ocean blues and purples. High-resolution, fantasy art.",
  "An enchanted forest at twilight, where fireflies dance around towering bioluminescent mushrooms, and an ancient glowing tree hums with magical energy. 8K, dreamlike atmosphere.",
  "A warrior angel with massive golden wings, standing on a floating island above a stormy sky, holding a blazing sword that illuminates the dark clouds. Ultra-detailed, epic fantasy.",
  "An anime android girl with sleek metallic limbs and glowing cybernetic eyes, standing in a neon-lit corridor of a futuristic spaceship, her circuits pulsating with energy. High-resolution, sci-fi anime.",
  "A time-traveling anime warrior with a glowing energy sword, standing before a swirling portal showing glimpses of different futuristic timelines. High-resolution, anime sci-fi, dramatic lighting.",
  "An anime swordsman with a crimson cloak, standing atop a ruined castle, his blade crackling with lightning as storm clouds gather behind him. Dynamic pose, anime action scene, ultra-detailed.",
  "A fierce anime bounty hunter with dual pistols, dodging laser blasts in a chaotic cyberpunk city, her trench coat flowing as she moves with lightning speed. High-energy action, cinematic composition.",
  "A young anime mage casting a powerful fire spell, their eyes glowing with arcane energy as swirling flames engulf the battlefield. Epic fantasy, high-resolution, ultra-detailed anime.",
  "An anime ninja leaping from rooftop to rooftop in a neon-lit futuristic Tokyo, his masked face revealing only piercing violet eyes. Dynamic pose, cinematic lighting, anime action.",
  "A soft-lit anime scene of a boy and girl sitting on a rooftop at sunset, sharing a pair of earphones as warm golden hues surround them. Romantic, ultra-detailed, heartwarming composition.",
];
