export const surpriseMePrompts = [
  "A striking close-up portrait of an elderly man with weathered skin, deep wrinkles, and piercing blue eyes, wearing a wide-brimmed hat under golden hour lighting, highly detailed and hyper-realistic.",
  "A glamorous studio portrait of a woman with glowing skin, sharp cheekbones, and emerald green eyes, wearing an elegant red gown, soft-focus background, and cinematic lighting.",
  "A serene mountain landscape with snow-capped peaks reflecting on a crystal-clear lake at sunrise, soft mist floating over the water, vibrant and natural colors, hyper-realistic",
  "A dense tropical rainforest scene with beams of sunlight breaking through the canopy, vibrant green foliage, moss-covered trees, and a crystal-clear stream winding through the frame",
  "A bustling street market at night in Tokyo, glowing neon signs in vibrant colors, people walking under umbrellas, and reflections shimmering on the wet pavement, ultra-detailed",
  "A candid black-and-white shot of a man sitting on a bench in a European cobblestone street, surrounded by pigeons, with soft natural lighting and a moody vintage tone",
  "A futuristic skyscraper with reflective glass panels under a vibrant sunset sky, captured at an upward angle, with stunning details and dynamic lighting",
  "An abandoned Gothic cathedral with ivy creeping up its walls, intricate stained glass windows, and dramatic sunlight streaming through broken arches, hyper-realistic and moody",
  "An extreme close-up of a dew-covered butterfly perched on a vibrant flower, with soft-focus background and intricate details of its wings and textures",
  "A crystal-clear macro shot of a droplet of water hanging from a leaf, refracting the colorful landscape in the background, with razor-sharp detail and smooth bokeh",
  "A majestic lion standing on a rocky outcrop at dusk, its mane flowing in the wind, with the savanna and a dramatic golden sunset in the background, hyper-realistic",
  "A snowy owl mid-flight over a frozen tundra, with feathers sharply detailed and icy air visibly swirling in the soft light, a highly detailed and natural composition",
  "A high-fashion editorial shot of a model in a flowing black gown standing in the middle of a desert, windswept hair, dramatic lighting, and a moody overcast sky",
  "A futuristic runway shoot with a model wearing avant-garde metallic clothing, neon lighting casting sharp shadows, and a sleek industrial background",
  "A dynamic action shot of a soccer player mid-kick during a match, dirt flying off the ground, intense facial expression, and a vibrant stadium background",
  "A cyclist speeding through a misty forest trail at sunrise, with motion blur in the background and sharp focus on the athlete and their gear",
  "A serene underwater view of a sea turtle gliding above a sandy ocean floor, with the surface rippling in the background and vivid blue tones",
  "An aerial view of a winding mountain road cutting through lush green valleys, with cars creating dynamic motion and dramatic shadows from the setting sun",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A drone shot of a tropical island surrounded by turquoise waters, white sandy beaches, and colorful coral reefs, with boats creating trails in the water",
  "A photo of a white fur monster standing in a purple room",
  "A Samurai riding a horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A breathtaking aerial view of a city skyline at twilight, with skyscrapers glowing in golden hues, reflections on the river, and a soft gradient sky, ultra-detailed and cinematic.",
  "A mysterious cyberpunk alleyway at night, neon signs casting vibrant colors, steam rising from grates, and a lone figure in a futuristic jacket walking through the scene, hyper-realistic.",
  "A mystical enchanted forest at dusk, with glowing bioluminescent plants, ethereal mist, and ancient twisted trees, a magical and atmospheric composition.",
  "A roaring waterfall cascading into a hidden jungle pool, surrounded by lush tropical vegetation, with sunlight streaming through the dense canopy, hyper-realistic and vibrant.",
  "A majestic bald eagle soaring above a vast canyon, with its wings fully extended, golden sunlight highlighting its feathers, and a dramatic sky in the background.",
  "A stunning futuristic cityscape with sleek, towering skyscrapers, flying vehicles, and neon holographic billboards, set under a vibrant dusk sky, ultra-detailed and dynamic.",
  "An astronaut standing on the surface of an alien planet, with a massive ringed gas giant in the sky, glowing blue crystals scattered across the rocky terrain, hyper-realistic sci-fi.",
  "A dramatic black-and-white portrait of a jazz musician playing the saxophone, smoke curling in the air, with moody lighting and a vintage film noir aesthetic.",
  "A stormy ocean scene with towering waves crashing against jagged rocks, a lighthouse standing resilient in the background, and dark, ominous clouds overhead, hyper-realistic.",
  "A vibrant carnival scene at night, with a Ferris wheel illuminated in rainbow lights, bustling crowds, and colorful confetti floating through the air, ultra-detailed and dynamic.",
  "A warrior in ancient samurai armor standing in a misty bamboo forest, katana in hand, with falling cherry blossoms and soft golden light filtering through the trees.",
  "A sleek futuristic race car speeding down a neon-lit highway, motion blur emphasizing its velocity, with a cyberpunk city in the background, ultra-detailed and dynamic.",
  "A tranquil autumn park scene with golden leaves covering the ground, a wooden bench under a vintage streetlamp, and a soft, warm glow from the evening sun.",
  "A surreal dreamscape with floating islands covered in lush greenery, waterfalls cascading into the sky, and a giant moon illuminating the ethereal landscape highly detailed digital art.",
  "A lone Viking warrior standing atop a snowy mountain peak, his fur cloak billowing in the wind, with a breathtaking view of a frozen fjord below, hyper-realistic and cinematic.",
  "A group of penguins waddling across an icy landscape, with the aurora borealis shimmering in the night sky, and a vast frozen ocean stretching into the horizon, ultra-detailed and natural.",
  "A dynamic parkour athlete mid-air between two skyscrapers, with city lights glowing below, captured in a breathtaking action shot with intense motion and energy.",
  "An elegant black panther prowling through a moonlit jungle, its sleek fur glistening, with glowing eyes and mist swirling around its powerful silhouette, hyper-realistic.",
  "A rustic countryside cottage covered in ivy, with warm light glowing from the windows, surrounded by a field of colorful wildflowers, and a dreamy sunset sky in the background.",
  "A post-apocalyptic desert wasteland with a lone survivor walking past rusted abandoned vehicles, sandstorms swirling, and a distant ruined city on the horizon, hyper-realistic.",
  "A celestial scene featuring a massive spiral galaxy with vibrant hues of blue and purple, countless stars, and glowing nebulae stretching across space, ultra-detailed and cosmic.",
  "A steampunk-inspired airship floating above a sprawling Victorian-era city, with intricate brass details, large propellers, and billowing clouds in the golden sunset sky, highly detailed.",
];
